// <auto-generated />
using System;
using DungeonHeros.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DungeonHeros.Migrations
{
    [DbContext(typeof(DungeonHerosDbContext))]
    [Migration("20220512142347_userInTeam")]
    partial class userInTeam
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DungeonHeros.Models.Dungeon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dungeon", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = ".../Images/cover.jpg",
                            Level = 0,
                            Name = "Les Terres Brules"
                        },
                        new
                        {
                            Id = 2,
                            Image = ".../Images/IceDJ.jpg",
                            Level = 0,
                            Name = "Cours du hibou"
                        },
                        new
                        {
                            Id = 3,
                            Image = ".../Images/Desert.jpg",
                            Level = 0,
                            Name = "Temple de hrakas"
                        },
                        new
                        {
                            Id = 4,
                            Image = ".../Images/Forest.jpg",
                            Level = 0,
                            Name = "Foret celeste"
                        });
                });

            modelBuilder.Entity("DungeonHeros.Models.DungeonMonstreRelation", b =>
                {
                    b.Property<int>("DungeonsId")
                        .HasColumnType("int");

                    b.Property<string>("MonstresNom")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NbrMonstre")
                        .HasColumnType("int");

                    b.HasKey("DungeonsId", "MonstresNom");

                    b.ToTable("DungeonMonstre", (string)null);

                    b.HasData(
                        new
                        {
                            DungeonsId = 1,
                            MonstresNom = "Kobold",
                            NbrMonstre = 5
                        },
                        new
                        {
                            DungeonsId = 1,
                            MonstresNom = "Ogre",
                            NbrMonstre = 2
                        },
                        new
                        {
                            DungeonsId = 1,
                            MonstresNom = "Golem d’os",
                            NbrMonstre = 1
                        },
                        new
                        {
                            DungeonsId = 1,
                            MonstresNom = "Serwaul",
                            NbrMonstre = 1
                        },
                        new
                        {
                            DungeonsId = 2,
                            MonstresNom = "Efrit",
                            NbrMonstre = 2
                        },
                        new
                        {
                            DungeonsId = 2,
                            MonstresNom = "Fafnir",
                            NbrMonstre = 1
                        },
                        new
                        {
                            DungeonsId = 2,
                            MonstresNom = "Hydre",
                            NbrMonstre = 1
                        },
                        new
                        {
                            DungeonsId = 2,
                            MonstresNom = "Vouivre",
                            NbrMonstre = 2
                        },
                        new
                        {
                            DungeonsId = 3,
                            MonstresNom = "Dark Lord",
                            NbrMonstre = 1
                        },
                        new
                        {
                            DungeonsId = 3,
                            MonstresNom = "Serwaul",
                            NbrMonstre = 5
                        },
                        new
                        {
                            DungeonsId = 4,
                            MonstresNom = "Araignée",
                            NbrMonstre = 2
                        },
                        new
                        {
                            DungeonsId = 4,
                            MonstresNom = "Chauve - Souris",
                            NbrMonstre = 2
                        },
                        new
                        {
                            DungeonsId = 4,
                            MonstresNom = "Loup Geant",
                            NbrMonstre = 1
                        });
                });

            modelBuilder.Entity("DungeonHeros.Models.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Classe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Endurance")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<int>("Force")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Placeholder_hero.jpg");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Hero", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Classe = "Magicien",
                            Endurance = 5,
                            Force = 2,
                            Image = ".../Images/nainVoleur.jpg",
                            Nom = "Torain",
                            Race = "Nain",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Classe = "Guerrier",
                            Endurance = 2,
                            Force = 5,
                            Image = ".../Images/orcGuerrier.jpg",
                            Nom = "Gurldac",
                            Race = "Orc",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Classe = "Archer",
                            Endurance = 4,
                            Force = 3,
                            Image = ".../Images/elfeArcher.jpg",
                            Nom = "Oldin",
                            Race = "Elf",
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            Classe = "Voleur",
                            Endurance = 6,
                            Force = 1,
                            Image = ".../Images/humainSorcier.jpg",
                            Nom = "Didier",
                            Race = "Humain",
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            Classe = "Voleur",
                            Endurance = 2,
                            Force = 4,
                            Image = ".../Images/nainVoleur.jpg",
                            Nom = "Gibli",
                            Race = "Nain",
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            Classe = "Archer",
                            Endurance = 1,
                            Force = 6,
                            Image = ".../Images/orcGuerrier.jpg",
                            Nom = "Gorduc",
                            Race = "Orc",
                            UserId = 3
                        },
                        new
                        {
                            Id = 7,
                            Classe = "Guerrier",
                            Endurance = 3,
                            Force = 2,
                            Image = ".../Images/elfeArcher.jpg",
                            Nom = "Aldin",
                            Race = "Elf",
                            UserId = 4
                        });
                });

            modelBuilder.Entity("DungeonHeros.Models.HeroTeamRelation", b =>
                {
                    b.Property<int>("IdTeam")
                        .HasColumnType("int");

                    b.Property<int>("IdHero")
                        .HasColumnType("int");

                    b.HasKey("IdTeam", "IdHero");

                    b.ToTable("HeroTeam", (string)null);

                    b.HasData(
                        new
                        {
                            IdTeam = 7,
                            IdHero = 1
                        },
                        new
                        {
                            IdTeam = 7,
                            IdHero = 2
                        },
                        new
                        {
                            IdTeam = 7,
                            IdHero = 3
                        },
                        new
                        {
                            IdTeam = 7,
                            IdHero = 4
                        },
                        new
                        {
                            IdTeam = 9,
                            IdHero = 5
                        },
                        new
                        {
                            IdTeam = 9,
                            IdHero = 6
                        },
                        new
                        {
                            IdTeam = 8,
                            IdHero = 7
                        });
                });

            modelBuilder.Entity("DungeonHeros.Models.Monstre", b =>
                {
                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Endurance")
                        .HasColumnType("int");

                    b.Property<int>("Force")
                        .HasColumnType("int");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Nom");

                    b.ToTable("Monster", (string)null);

                    b.HasData(
                        new
                        {
                            Nom = "Araignée",
                            Avatar = ".../Images/Monstre/spider.jpg",
                            Endurance = 2,
                            Force = 2,
                            Race = "Animal"
                        },
                        new
                        {
                            Nom = "Chauve - Souris",
                            Avatar = ".../Images/Monstre/bat.jpg",
                            Endurance = 2,
                            Force = 1,
                            Race = "Animal"
                        },
                        new
                        {
                            Nom = "Dark Lord",
                            Avatar = ".../Images/Monstre/DarkLord.png",
                            Endurance = 20,
                            Force = 20,
                            Race = "Démon"
                        },
                        new
                        {
                            Nom = "Efrit",
                            Avatar = ".../Images/Monstre/efrit.jpg",
                            Endurance = 4,
                            Force = 4,
                            Race = "Monstre"
                        },
                        new
                        {
                            Nom = "Fafnir",
                            Avatar = ".../Images/Monstre/Fafnir.png",
                            Endurance = 7,
                            Force = 9,
                            Race = "Dragon"
                        },
                        new
                        {
                            Nom = "Golem d’os",
                            Avatar = ".../Images/Monstre/Bone_Golem.jpg",
                            Endurance = 3,
                            Force = 5,
                            Race = "Monstre"
                        },
                        new
                        {
                            Nom = "Grougaloragran",
                            Avatar = ".../Images/Monstre/grougaloragran.jpg",
                            Endurance = 12,
                            Force = 4,
                            Race = "Dragon"
                        },
                        new
                        {
                            Nom = "Hydre",
                            Avatar = ".../Images/Monstre/hydra.jpg",
                            Endurance = 11,
                            Force = 5,
                            Race = "Monstre"
                        },
                        new
                        {
                            Nom = "Kobold",
                            Avatar = ".../Images/Monstre/kobold.jpg",
                            Endurance = 4,
                            Force = 2,
                            Race = "Monstre"
                        },
                        new
                        {
                            Nom = "Loup Geant",
                            Avatar = ".../Images/Monstre/wolf.jpg",
                            Endurance = 3,
                            Force = 4,
                            Race = "Animal"
                        },
                        new
                        {
                            Nom = "Ogre",
                            Avatar = ".../Images/Monstre/ogre.jpg",
                            Endurance = 3,
                            Force = 1,
                            Race = "Monstre"
                        },
                        new
                        {
                            Nom = "Serwaul",
                            Avatar = ".../Images/Monstre/serwaul.jpeg",
                            Endurance = 1,
                            Force = 7,
                            Race = "Démon"
                        },
                        new
                        {
                            Nom = "Vouivre",
                            Avatar = ".../Images/Monstre/wyvern.jpg",
                            Endurance = 15,
                            Force = 10,
                            Race = "Dragon"
                        });
                });

            modelBuilder.Entity("DungeonHeros.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Teams", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Score = 0,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Score = 15,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Score = 10,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Score = 10,
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            Score = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            Score = 20,
                            UserId = 3
                        },
                        new
                        {
                            Id = 7,
                            Score = 45,
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            Score = 25,
                            UserId = 3
                        },
                        new
                        {
                            Id = 9,
                            Score = 30,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("DungeonHeros.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomHero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Mail = "admin",
                            NomHero = "admin",
                            Password = "admin"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(2000, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Mail = "ghostkiller598r@gmail.com",
                            NomHero = "Ghostkiller",
                            Password = "qwerty"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(2000, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Mail = "nathanlombardelli@hotmail.com",
                            NomHero = "Ghost",
                            Password = "qwerty"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(1980, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Mail = "fabriceetverodehous@hotmail.com",
                            NomHero = "LOU",
                            Password = "FLloulou"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(1982, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Mail = "dejardinveronique.b159@hotmail.com",
                            NomHero = "Icare",
                            Password = "dejdej"
                        });
                });

            modelBuilder.Entity("DungeonHeros.Models.Hero", b =>
                {
                    b.HasOne("DungeonHeros.Models.User", null)
                        .WithMany("Heros")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("DungeonHeros.Models.User", b =>
                {
                    b.Navigation("Heros");
                });
#pragma warning restore 612, 618
        }
    }
}
